# -*- coding: utf-8 -*-
"""MSDS_570_Imputation_for_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcFCsboZ1ar927qQYJthOZhmWcIik7Q2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

# reading data
data = pd.read_csv('/content/drive/MyDrive/life_expectancy.csv')
data.head()

data_drop_corruption = data.copy()
data_drop_corruption.head()

data_drop = data_drop_corruption.drop(columns = 'Corruption')

data_merge_life_expect = data_drop.iloc[:, [2, 4, 5]]
data_merge_life_expect.info()

target_data_nan_life_expect = data_drop.groupby(['Region', 'Year']) ['Life Expectancy World Bank'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_life_expect.info()

data_merge_prevalence_of_under = data_drop.iloc[:, [2, 4, 6]]
data_merge_prevalence_of_under.info()

target_data_nan_prevalence_of_under = data_drop.groupby(['Region', 'Year']) ['Prevelance of Undernourishment'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_prevalence_of_under.info()

data_merge_health_expenditure = data_drop.iloc[:, [2, 4, 8]]
data_merge_health_expenditure.info()

target_data_nan_health_expenditure = data_drop.groupby(['Region', 'Year']) ['Health Expenditure %'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_health_expenditure.info()

data_merge_education_expenditure = data_drop.iloc[:, [2, 4, 9]]
# 1090 nan, contemplating whether filling this nan is even worth it.
data_merge_education_expenditure.info()

target_data_nan_education_expenditure = data_drop.groupby(['Region', 'Year']) ['Education Expenditure %'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_education_expenditure.info()
data_drop['Education Expenditure %'].isna().sum()

# Forward fill ffill()
data_drop['Education Expenditure %'] = data_drop.groupby('Region')['Education Expenditure %'].transform(lambda x: x.sort_values().ffill())

# Backward fill bfill()
data_drop['Education Expenditure %'] = data_drop.groupby('Region')['Education Expenditure %'].transform(lambda x: x.sort_values().bfill())

# Backward fill
#data_drop['Education Expenditure %'].fillna(data_drop['Education Expenditure %'].mean(), inplace=True)

target_data_nan_education_expenditure_updated = data_drop['Education Expenditure %']

target_data_nan_education_expenditure_updated.info()

target_data_nan_education_expenditure.isna().any()

target_data_nan_education_expenditure_updated.isna().any()

data_merge_unemployment = data_drop.iloc[:, [2, 4, 10]]
# similar to the previous column, 1247 nan. Thinking if i should fill this nan
data_merge_unemployment.info()

target_data_nan_unemployment = data_drop.groupby(['Region', 'Year']) ['Unemployment'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_unemployment.info()

data_merge_sanitation = data_drop.iloc[:, [2, 4, 11]]
# similar to the previous column, 1247 nan. Thinking if i should fill this nan
data_merge_sanitation.info()

target_data_nan_sanitation = data_drop.groupby(['Region', 'Year']) ['Sanitation'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_sanitation.info()

data_merge_CO2 = data_drop.iloc[:, [2, 4, 7]]
data_merge_CO2.isna().info()

target_data_nan_CO2 = data_drop.groupby(['Region', 'Year']) ['CO2'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_CO2.info()

data_drop['CO2'] = target_data_nan_CO2
data_drop['Education Expenditure %'] = target_data_nan_education_expenditure_updated
data_drop['Health Expenditure %'] = target_data_nan_health_expenditure
data_drop['Prevelance of Undernourishment'] = target_data_nan_prevalence_of_under
data_drop['Unemployment'] = target_data_nan_unemployment
data_drop['Life Expectancy World Bank'] = target_data_nan_life_expect
data_drop['Sanitation'] = target_data_nan_sanitation

data_drop.info()

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# %matplotlib inline

catg_data_drop = data_drop.select_dtypes(include=object)
catg_data_drop.info()

num_data_drop = data_drop.select_dtypes(exclude=object)
num_data_drop.info()

life_expectancy_mean_global = data_drop.groupby('Year')['Life Expectancy World Bank'].mean()
life_expectancy_mean_global

# Target variable (Life Expectancy World Bank) trend across year for all region

plt.figure(figsize=(16, 8), dpi=300)

# Plot data
plt.plot(life_expectancy_mean_global.index, life_expectancy_mean_global.values, marker='o', linestyle='-', color='b')

# Specify ticks for x- and y-axis
plt.xticks(np.arange(2000, 2020, 1), rotation=70)
plt.yticks(np.arange(65, 75, 1))

# Add title and label for y-axis
plt.title('Plot of mean global life Expectancy with respect to year from 2001 to 2019 ', fontsize=16)
plt.ylabel('Life Expectancy', fontsize=14)

# Add grid
plt.grid()

# Add legend
plt.legend(loc='upper left')

# Show plot
plt.show()

# Taking the mean of life expectancy for each year across all region
life_expectancy_mean_region_global = data_drop.groupby('Year')['Life Expectancy World Bank'].mean()
life_expectancy_mean_region_global

# Confirmation of life expectancy globally from 2001 to 2019
np.mean(data_drop['Life Expectancy World Bank'])

# Histogram Plot of mean life expectancy from 2001 - 2019
life_expectancy_mean_region_global = data_drop.groupby('Region')['Life Expectancy World Bank'].mean()
life_expectancy_mean_region_global

# Looking at communicable and noncommunicable diseases per year on all region
life_expectancy_mean_region_global_disease = data_drop.iloc[:, [2, 4, 5, 13, 14]].groupby(['Region', 'Year', 'NonCommunicable'])['Life Expectancy World Bank'].mean()
life_expectancy_mean_region_global_disease

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(life_expectancy_mean_region_global_disease)

region_year = data_drop.iloc[:, [0, 2, 4, 5]]
East_Asia_year = region_year[(region_year['Region'] == 'East Asia & Pacific') & (region_year['Year'] == 2002)].sort_values('Life Expectancy World Bank')
East_Asia_year

np.mean(East_Asia_year['Life Expectancy World Bank'])

print('Number of country in East Asia & Pacific is:' , region_year[region_year['Region'] == 'East Asia & Pacific']['Country Name'].nunique())

data_drop

plt.figure(figsize=(16, 8), dpi=300)

countries = East_Asia_year['Country Name']
life_expectancy_values = East_Asia_year['Life Expectancy World Bank']

n_groups = len(countries)
index = np.arange(n_groups)
bar_width = 0.35

plt.bar(index - bar_width/2, life_expectancy_values, bar_width, label='Life Expectancy World Bank', color='grey')

plt.xticks(index, countries, rotation=90)
max_value = (life_expectancy_values.max())
y_upper_limit = max_value

plt.ylim(0, y_upper_limit)
plt.yticks(np.arange(0, 100, 10))

ax = plt.gca()

ax.set_yticks(np.arange(0, 100, 10), minor=True)

plt.title('Life Expectancy vs. Injuries per Country in East Asia & Pacific (2002)')
#plt.xlabel('Country Name', fontsize=12)
plt.ylabel('Life Span', fontsize=12)

plt.legend(fontsize=10)
plt.tight_layout()
plt.show()

communicable_year = data_drop.iloc[:, [0, 2, 4, 5, 11, 13]]
Latin_America_year = communicable_year[(communicable_year['Region'] == 'Latin America & Caribbean') & (communicable_year['Year'] == 2008)].sort_values('Communicable')
Latin_America_year

np.mean(Latin_America_year['Life Expectancy World Bank'])

print('Number of country in Latin America & Caribbean is:' , communicable_year[communicable_year['Region'] == 'Latin America & Caribbean']['Country Name'].nunique())

life_expectancy_values.dtypes

plt.figure(figsize=(16, 8), dpi=300)

countries = Latin_America_year['Country Name']
life_expectancy_data = Latin_America_year['Life Expectancy World Bank']
sanitation_values = Latin_America_year['Sanitation']

n_groups = len(countries)
index = np.arange(n_groups)
bar_width = 0.35

plt.bar(index - bar_width/2, life_expectancy_data, bar_width, label='Life Expectancy World Bank', color='brown')
plt.bar(index + bar_width/2, sanitation_values, bar_width, label='Sanitation', color='orange')

plt.xticks(index, countries, rotation=90)
max_value = max(life_expectancy_data.max(), sanitation_values.max())
y_upper_limit = max_value + 10

plt.ylim(0, y_upper_limit)

plt.yticks(np.arange(0, y_upper_limit + 10, 10))

ax = plt.gca()

ax.set_yticks(np.arange(0, y_upper_limit + 10, 10), minor=True)

plt.title('Life Expectancy and Sanitation in Latin America (2008)')
#plt.xlabel('Country Name', fontsize=12)
plt.ylabel('Life Span / Sanitation (%)', fontsize=12)

plt.legend(fontsize=10)
plt.tight_layout()
plt.show()

nourishment_year = data_drop.iloc[:, [0, 2, 4, 5, 6, 9, 10]]
Sub_Saharan_year = nourishment_year[(nourishment_year['Region'] == 'Sub-Saharan Africa') & (nourishment_year['Year'] == 2001)].sort_values('Unemployment')
Sub_Saharan_year

np.mean(Sub_Saharan_year['Life Expectancy World Bank'])

"""closed bracket bug on this line"""

print('Number of country in Sub Saharan Africa is:' , nourishment_year[nourishment_year['Region'] == 'Sub-Saharan Africa']['Country Name'].nunique())

plt.figure(figsize=(20, 16), dpi=300)

countries = Sub_Saharan_year['Country Name']
life_expectancy_data = Sub_Saharan_year['Life Expectancy World Bank']
undernourishment_values = Sub_Saharan_year['Prevelance of Undernourishment']
education_values = Sub_Saharan_year['Education Expenditure %']
unemployment_values = Sub_Saharan_year['Unemployment']

n_groups = len(countries)
index = np.arange(n_groups)
bar_width = 0.2

plt.bar(index - bar_width * 1.5, life_expectancy_data, bar_width, label='Life Expectancy World Bank', color='orange')
plt.bar(index - bar_width * 0.5, undernourishment_values, bar_width, label='Prevelance of Undernourishment', color='green')
plt.bar(index + bar_width * 0.5, education_values, bar_width, label='Education Expenditure %', color='black')
plt.bar(index + bar_width * 1.5, unemployment_values, bar_width, label='Unemployment', color='red')

plt.xticks(index, countries, rotation=90)
max_value = max(life_expectancy_data.max(), undernourishment_values.max(), education_values.max(), unemployment_values.max())
y_upper_limit = max_value # Add some padding for better visualization

plt.ylim(0, y_upper_limit)

plt.yticks(np.arange(0, y_upper_limit + 10, 5))

ax = plt.gca()

ax.set_yticks(np.arange(0, y_upper_limit + 10, 10), minor=True)

plt.title('Life Expectancy, Undernourishment, Education Expenditure, and Unemployment in Sub-Saharan Africa (2001)')
plt.ylabel('Values (%)', fontsize=12)

plt.legend(fontsize=10)
plt.tight_layout()
plt.show()

noncommunicable_year = data_drop.iloc[:, [0, 2, 4, 5, 7, 8, 14]]
noncommunicable_year = noncommunicable_year[(noncommunicable_year['Region'] == 'South Asia') & (noncommunicable_year['Year'] == 2012)].sort_values('Health Expenditure %')
noncommunicable_year

plt.figure(figsize=(16, 8), dpi=300)

countries = noncommunicable_year['Country Name']
life_expectancy_data = noncommunicable_year['Life Expectancy World Bank']
health_values= noncommunicable_year['Health Expenditure %']

n_groups = len(countries)
index = np.arange(n_groups)
bar_width = 0.35

plt.bar(index - bar_width/2, life_expectancy_data, bar_width, label='Life Expectancy World Bank', color='brown')
plt.bar(index + bar_width * 0.5, health_values, bar_width, label='Health Expenditure %', color='black')

plt.xticks(index, countries, rotation=90)
max_value = max(life_expectancy_data.max(), health_values.max())
y_upper_limit = max_value + 10

plt.ylim(0, y_upper_limit)

plt.yticks(np.arange(0, y_upper_limit + 10, 10))

ax = plt.gca()

ax.set_yticks(np.arange(0, y_upper_limit + 10, 10), minor=True)

plt.title('Life Expectancy and Sanitation in South Asia (2012)')
#plt.xlabel('Country Name', fontsize=12)
plt.ylabel('Life Span / CO2 (%)', fontsize=12)

plt.legend(fontsize=10)
plt.tight_layout()
plt.show();

CO2 = data_drop.iloc[:, [0, 2, 4, 5, 7, 8, 14]]
CO2_long = CO2[(data_drop['CO2'] > 300000) & (CO2['Year'] == 2012)].sort_values(['Life Expectancy World Bank'])
CO2_long

np.mean(data_drop['CO2'])

display(CO2_long)

x = data_drop['Region'].unique()
x

#Using this to determine the column (irrelevant and redudant)
data_drop.info()

# Create figure
plt.figure(figsize=(10, 6), dpi=150)

# Create histogram of the overall 'Life Expectancy World Bank' values
plt.hist(data_drop['Life Expectancy World Bank'], bins=30, edgecolor='black', color='blue')

# Add labels and title
plt.xlabel('Life Expectancy World Bank')
plt.ylabel('Frequency')
plt.title('Distribution of Life Expectancy World Bank (2001-2019)')

# Add vertical lines for mean and median (optional, but good for distribution analysis)
mean_le = data_drop['Life Expectancy World Bank'].mean()
median_le = data_drop['Life Expectancy World Bank'].median()
plt.axvline(mean_le, color='red', linestyle='dashed', linewidth=1, label=f'Mean: {mean_le:.2f}')
plt.axvline(median_le, color='green', linestyle='dashed', linewidth=1, label=f'Median: {median_le:.2f}')

# Add grid and legend
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()

# Show plot
plt.show();

data_drop.info()

life_expectancy_mean_region_global_per_year =  data_drop.iloc[:, [0, 2, 3, 4, 5]]
life_expectancy_mean_region_global_per_region = life_expectancy_mean_region_global_per_year[(life_expectancy_mean_region_global_per_year['Region'] == 'South Asia') & (life_expectancy_mean_region_global_per_year['Country Name'] == 'India')].sort_values(['Country Name', 'Year'])
life_expectancy_mean_region_global_per_region

import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8), dpi=300)

plot_df = life_expectancy_mean_region_global_per_region.reset_index()


unique_income_groups = plot_df['IncomeGroup'].unique()
colors = plt.cm.viridis(np.linspace(0, 1, len(unique_income_groups)))

for i, group in enumerate(unique_income_groups):
    subset = plot_df[plot_df['IncomeGroup'] == group]
    plt.scatter(
        x = subset['Life Expectancy World Bank'],
        y = subset['Year'],
        color=colors[i],
        s=50,
        alpha=0.8,
        edgecolors="white",
        linewidth=1,
        label=group
    )

plt.xlabel("Mean Life Expectancy")
plt.ylabel("Year")
plt.title("Mean Life Expectancy by Year, Region, and Income Group of India Ranging from 2001 to 2019")

min_le = plot_df['Life Expectancy World Bank'].min()
max_le = plot_df['Life Expectancy World Bank'].max()
plt.xlim(min_le - (max_le - min_le) * 0.1, max_le + (max_le - min_le) * 0.1)

plt.yticks(plot_df['Year'].unique())

plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Income Group', bbox_to_anchor=(1.05, 1), loc='upper left') # Now legend works outside plot area

plt.tight_layout()
plt.show();

idx = pd.IndexSlice
life_expectancy_mean_region_global_per_country = life_expectancy_mean_region_global_per_year[
    (life_expectancy_mean_region_global_per_year['Region'] == 'Sub-Saharan Africa') &
    (life_expectancy_mean_region_global_per_year['Country Name'].isin(['Eritrea', 'Ethiopia', 'Sudan']))
].sort_values(by='Life Expectancy World Bank', ascending=True)
life_expectancy_mean_region_global_per_country

import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8), dpi=300)

plot_df = life_expectancy_mean_region_global_per_country.reset_index()


unique_income_groups = plot_df['Country Name'].unique()
colors = plt.cm.viridis(np.linspace(0, 1, len(unique_income_groups))) # i tried changing the variable to unique_countries_group but it doesn't run. Iwas first using unique income group

for i, group in enumerate(unique_income_groups):
    subset = plot_df[plot_df['Country Name'] == group]
    plt.scatter(
        x = subset['Life Expectancy World Bank'],
        y = subset['Year'],
        color=colors[i],
        s=50,
        alpha=0.8,
        edgecolors="maroon",
        linewidth=1,
        label=group
    )

plt.xlabel("Mean Life Expectancy")
plt.ylabel("Year")
plt.title("Mean Life Expectancy By Year for 3 neighboring countries (Ethopia, Eritrea and Sudan) in Sub-Sahara Ranging from 2001 to 2019")

min_le = plot_df['Life Expectancy World Bank'].min()
max_le = plot_df['Life Expectancy World Bank'].max()
plt.xlim(min_le - (max_le - min_le) * 0.1, max_le + (max_le - min_le) * 0.1)

plt.yticks(plot_df['Year'].unique())

plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Country Name', bbox_to_anchor=(1.05, 1), loc='upper left') # Now legend works outside plot area

plt.tight_layout()
plt.show();

life_expectancy_mean_region_global_per_year =  data_drop.iloc[:, [0, 2, 3, 4, 5, 6]]
life_expectancy_mean_region_global_per_nourishment = life_expectancy_mean_region_global_per_year[(life_expectancy_mean_region_global_per_year['Region'] == 'East Asia & Pacific') & (life_expectancy_mean_region_global_per_year['Country Name'] == 'China')].sort_values(['Country Name', 'Year'])
life_expectancy_mean_region_global_per_nourishment

# removed all the package and re-run with all packages installed in one cell and imported

plt.figure(figsize=(12, 8), dpi=300)

plot_df = life_expectancy_mean_region_global_per_nourishment.reset_index()


unique_income_groups = plot_df['IncomeGroup'].unique()
colors = plt.cm.viridis(np.linspace(0, 1, len(unique_income_groups)))

for i, group in enumerate(unique_income_groups):
    subset = plot_df[plot_df['IncomeGroup'] == group]
    plt.scatter(
        x = subset['Life Expectancy World Bank'],
        y = subset['Year'],
        color=colors[i],
        s=50,
        alpha=0.8,
        edgecolors="white",
        linewidth=1,
        label=group
    )

plt.xlabel("Mean Life Expectancy")
plt.ylabel("Year")
plt.title("Mean Life Expectancy by Year, Region, and Income Group of China Ranging from 2001 to 2019")

min_le = plot_df['Life Expectancy World Bank'].min()
max_le = plot_df['Life Expectancy World Bank'].max()
plt.xlim(min_le - (max_le - min_le) * 0.1, max_le + (max_le - min_le) * 0.1)

plt.yticks(plot_df['Year'].unique())

plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Income Group', bbox_to_anchor=(1.05, 1), loc='upper left') # Now legend works outside plot area

plt.tight_layout()
plt.show();

idx = pd.IndexSlice
temp_df_for_nourishment = data_drop.iloc[:, [0, 2, 3, 4, 5, 6]]
life_expectancy_mean_region_global_per_country_nourish = temp_df_for_nourishment[
    (temp_df_for_nourishment['Region'] == 'South Asia') &
    (temp_df_for_nourishment['Country Name'].isin(['Sri Lanka', 'Nepal', 'Bangladesh', 'Bhutan', 'Maldives', 'Pakistan', 'India', 'Afghanistan'])) &
    (temp_df_for_nourishment['Year'])
].sort_values(by='Prevelance of Undernourishment', ascending=True)
life_expectancy_mean_region_global_per_country_nourish

plt.figure(figsize=(12, 8), dpi=300)

plot_df = life_expectancy_mean_region_global_per_country_nourish.reset_index()


unique_income_groups = plot_df['Country Name'].unique()
colors = plt.cm.viridis(np.linspace(0, 1, len(unique_income_groups)))

for i, group in enumerate(unique_income_groups):
    subset = plot_df[plot_df['Country Name'] == group]
    plt.scatter(
        x = subset['Life Expectancy World Bank'],
        y = subset['Year'],
        color=colors[i],
        s=50,
        alpha=0.8,
        edgecolors="red",
        linewidth=1,
        label=group
    )

plt.xlabel("Mean Life Expectancy")
plt.ylabel("Year")
plt.title("Mean Life Expectancy by Year, Region, Income Group and Prevelance of Nourishment seeen in South Asia Ranging from 2001 to 2019")

min_le = plot_df['Life Expectancy World Bank'].min()
max_le = plot_df['Life Expectancy World Bank'].max()
plt.xlim(min_le - (max_le - min_le) * 0.1, max_le + (max_le - min_le) * 0.1)

plt.yticks(plot_df['Year'].unique())

plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Country Name', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show();

life_expectancy_mean_region_global_per_year =  data_drop.iloc[:, [0, 2, 3, 4, 5, 8, 13, 14]]
life_expectancy_mean_region_global_per_health = life_expectancy_mean_region_global_per_year[(life_expectancy_mean_region_global_per_year['Region'] == 'East Asia & Pacific') & (life_expectancy_mean_region_global_per_year['Country Name'] == 'Philippines') &  (life_expectancy_mean_region_global_per_year['Health Expenditure %'] > 2.8)].sort_values(['Country Name', 'Year'])
life_expectancy_mean_region_global_per_health

plt.figure(figsize=(12, 8), dpi=300)

plot_df = life_expectancy_mean_region_global_per_health.reset_index()

# Since plot_df already contains data for a single country (Philippines)
# and likely a single income group, we can plot directly without a complex loop.
# If you intend to compare multiple countries/income groups, the filtering for
# 'life_expectancy_mean_region_global_per_health' needs to be adjusted first.

# Get the country name for the label
country_name_for_label = plot_df['Country Name'].iloc[0] if not plot_df.empty else 'Unknown Country'

plt.scatter(
    x = plot_df['Life Expectancy World Bank'],
    y = plot_df['Health Expenditure %'],
    color='red', # You can choose a specific color
    s=50,
    alpha=0.8,
    edgecolors="white",
    linewidth=1,
    label=country_name_for_label
)

plt.xlabel("Life Expectancy World Bank")
plt.ylabel("Health Expenditure %")
plt.title(f"Life Expectancy vs. Health Expenditure % for {country_name_for_label} (2001-2019)")

min_le = plot_df['Life Expectancy World Bank'].min()
max_le = plot_df['Life Expectancy World Bank'].max()
plt.xlim(min_le - (max_le - min_le) * 0.1, max_le + (max_le - min_le) * 0.1)

# Removed explicit yticks to let matplotlib handle them based on 'Health Expenditure %' data
# plt.yticks(plot_df['Year'].unique())

plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Country Name', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show();

idx = pd.IndexSlice
life_expectancy_mean_region_global_per_country_health_expend = life_expectancy_mean_region_global_per_year[(life_expectancy_mean_region_global_per_year['Region'] == 'East Asia & Pacific') & (life_expectancy_mean_region_global_per_year['Year'] == 2019)].sort_values(by=['Health Expenditure %', 'Life Expectancy World Bank'], ascending=True)
life_expectancy_mean_region_global_per_country_health_expend.head()

plt.figure(figsize=(20, 16), dpi=300)

countries = life_expectancy_mean_region_global_per_country_health_expend['Country Name']
life_expectancy_data = life_expectancy_mean_region_global_per_country_health_expend['Life Expectancy World Bank']
health_spending_values = life_expectancy_mean_region_global_per_country_health_expend['Health Expenditure %']
communicable_values = life_expectancy_mean_region_global_per_country_health_expend['Communicable']
noncommunicable_values = life_expectancy_mean_region_global_per_country_health_expend['NonCommunicable']

# Calculate total disease DALYs
total_disease_dalys = communicable_values + noncommunicable_values

n_groups = len(countries)
index = np.arange(n_groups)
bar_width = 0.2

# Plotting bars side-by-side with distinct x-positions
# Using small positive values for log scale visualization
# Add a small constant to zero/near-zero values if they exist, to allow plotting on a log scale
# Ensure all values are positive for log scale
life_expectancy_data_log = life_expectancy_data.apply(lambda x: x if x > 0 else 0.01)
health_spending_values_log = health_spending_values.apply(lambda x: x if x > 0 else 0.01)
total_disease_dalys_log = total_disease_dalys.apply(lambda x: x if x > 0 else 0.01)

plt.bar(index - bar_width * 1.0, life_expectancy_data_log, bar_width, label='Life Expectancy World Bank', color='orange')
plt.bar(index, health_spending_values_log, bar_width, label='Health Expenditure %', color='blue')
plt.bar(index + bar_width * 1.0, total_disease_dalys_log, bar_width, label='Total Disease DALYs', color='red')

plt.xticks(index, countries, rotation=90)

# Apply logarithmic scale to the y-axis
plt.yscale('log')

# Set dynamic y-axis limits for better visualization on log scale, ensuring a positive minimum
min_val = min(life_expectancy_data_log.min(), health_spending_values_log.min(), total_disease_dalys_log.min())
max_val = max(life_expectancy_data_log.max(), health_spending_values_log.max(), total_disease_dalys_log.max())
plt.ylim(max(0.1, min_val / 2), max_val * 2)

plt.title('Life Expectancy, Health Expenditure, and Total Disease DALYs (2019)', fontsize=16)
plt.ylabel('Value (Log Scale)', fontsize=12)

plt.legend(fontsize=10)
plt.tight_layout()
plt.show();

life_expectancy_mean_region_global_per_country_health_expend.info()

data_drop.info()

life_expectancy_mean_region_global =  data_drop.iloc[:, [0, 2, 4, 5, 6]]
life_expectancy_mean_middle_east = life_expectancy_mean_region_global[(life_expectancy_mean_region_global['Region'] == 'Middle East & North Africa') & (life_expectancy_mean_region_global['Year'] == 2019)].sort_values('Life Expectancy World Bank')
life_expectancy_mean_middle_east

plt.figure(figsize=(16, 8), dpi=300)

countries = life_expectancy_mean_middle_east['Country Name']
life_expectancy_data = life_expectancy_mean_middle_east['Life Expectancy World Bank']
undernourishment_values= life_expectancy_mean_middle_east['Prevelance of Undernourishment']

n_groups = len(countries)
index = np.arange(n_groups)
bar_width = 0.35

plt.bar(index - bar_width/2, life_expectancy_data, bar_width, label='Life Expectancy World Bank', color='brown')
plt.bar(index + bar_width * 0.5, undernourishment_values, bar_width, label='Prevelance of Undernourishment', color='red')

plt.xticks(index, countries, rotation=90)
max_value = max(life_expectancy_data.max(), undernourishment_values.max())
y_upper_limit = max_value + 10

plt.ylim(0, y_upper_limit)

plt.yticks(np.arange(0, y_upper_limit + 10, 10))

ax = plt.gca()

ax.set_yticks(np.arange(0, y_upper_limit + 10, 10), minor=True)

plt.title('Life Expectancy and Prevelance of Undernourishment in Middle East & North Africa (2019)')
#plt.xlabel('Country Name', fontsize=12)
plt.ylabel('Life Span / % Undernourishment', fontsize=12)

plt.legend(fontsize=10)
plt.tight_layout()
plt.show();

catg_data_drop.info()

region_pie = data_drop.groupby(['Region', 'Country Name'])['Country Code'].count()
region_pie

region_income = catg_data_drop[['Region', 'IncomeGroup']].groupby(['Region'])
count_region = region_income.value_counts()
count_region

# Create figure
plt.figure(figsize=(16, 9), dpi=300)

# Create pie plot
plt.pie(count_region.values, labels=count_region.index, autopct='%.0f%%', pctdistance = 0.85, startangle = 85, rotatelabels=True)

# Add title
label = 'Percentage of Income Class across Region'
#plt.title('Percentage of Income Class across Region')

# add a white circle at the center
my_circle=plt.Circle( (0,2), 0.7)
p=plt.gcf()
p.gca().add_artist(my_circle)
# Show plot
plt.show();

life_expectancy_mean_region_year = data_drop.groupby(['Region', 'Year'])['Life Expectancy World Bank'].mean()
life_expectancy_mean_region_year

# Create figure
plt.figure(figsize=(12, 8), dpi=300)


life_expectancy_by_region_year = life_expectancy_mean_region_year.unstack(level='Region')

# Prepare x and y values for stackplot
x_values = life_expectancy_by_region_year.index
y_values = [life_expectancy_by_region_year[col].values for col in life_expectancy_by_region_year.columns]
labels = life_expectancy_by_region_year.columns

# Create stacked area chart
plt.stackplot(x_values, *y_values, labels=labels)

# Add legend
plt.legend(title='Region', bbox_to_anchor=(1.05, 1), loc='upper left')

# Add labels and title
plt.xlabel('Year')
plt.ylabel('Life Expectancy World Bank')
plt.title('Mean Life Expectancy Trend by Region (2001-2019)')

# Add ticks
plt.xticks(np.arange(2000, 2020, 1), rotation=70)
plt.yticks(np.arange(65, 75, 1))

# Add grid
plt.grid(True)

# Show plot
plt.tight_layout()
plt.show();

"""Use boxplot multiple to create a box plot for region and life expectancy showing the mean, median of that region"""

data_drop.info()

data_drop['CO2']

a = target_data_nan_CO2
b =  target_data_nan_education_expenditure_updated
c = target_data_nan_health_expenditure
d = target_data_nan_prevalence_of_under
e = target_data_nan_unemployment
f = target_data_nan_life_expect
g = target_data_nan_sanitation


data = [g,f]

# Box plot
fig = plt.figure(figsize =(10, 7))



# Creating axes instance
ax = fig.add_axes([0, 0, 1, 1])

# Creating plot
bp = ax.boxplot(data,patch_artist=True)

colors = ['tan', 'green']

for patch, color in zip(bp['boxes'], colors):
    patch.set_facecolor(color)

plt.xticks([1, 2], ['sanitation', "life expectancy"], rotation=0)

# show plot
plt.show()

region_life = data_drop[['Region', 'Life Expectancy World Bank']].groupby(['Region'])
region_life.describe()

region_for_boxplot = (data_drop.groupby('Region')['Life Expectancy World Bank'].agg(list))
region_for_boxplot

x = region_life['Life Expectancy World Bank']

data = [x]

# Box plot
fig = plt.figure(figsize =(10, 7))

# Get the labels for the x-axis (carrier codes)
labels = region_for_boxplot.index.tolist()

# Convert the Series of lists to a list of arrays for matplotlib boxplot
plot_data = region_for_boxplot.values.tolist()

# Create the figure and axes for the box plot
fig, ax = plt.subplots(figsize=(12, 6), dpi=150)

# Create the box plot
bp = ax.boxplot(plot_data, patch_artist=True, vert=True) # vert=True for vertical boxes

# Customize colors for the boxes (optional, but good for visual distinction)
colors = plt.cm.get_cmap('tab10', len(labels)) # Using a colormap for distinct colors
for patch, color in zip(bp['boxes'], colors.colors):
    patch.set_facecolor(color)



ax.set_xticks(np.arange(1, len(labels) + 1))
ax.set_xticklabels(labels, rotation=90, ha='right')

plt.ylabel('Life Expectancy')
plt.xlabel('Region')
plt.title('Life Expectancy by Region')
# show plot
plt.show();

year_life = data_drop[['Year', 'Life Expectancy World Bank']].groupby(['Year'])
year_life.describe()

year_for_boxplot = (data_drop.groupby('Year')['Life Expectancy World Bank'].agg(list))
year_for_boxplot

x = year_life['Life Expectancy World Bank']

data = [x]

# Box plot
fig = plt.figure(figsize =(10, 7))

# Get the labels for the x-axis (carrier codes)
labels = year_for_boxplot.index.tolist()

# Convert the Series of lists to a list of arrays for matplotlib boxplot
plot_data = year_for_boxplot.values.tolist()

# Create the figure and axes for the box plot
fig, ax = plt.subplots(figsize=(12, 6), dpi=150)

# Create the box plot
bp = ax.boxplot(plot_data, patch_artist=True, vert=True) # vert=True for vertical boxes

# Customize colors for the boxes (optional, but good for visual distinction)
colors = plt.cm.get_cmap('tab10', len(labels)) # Using a colormap for distinct colors
for patch, color in zip(bp['boxes'], colors.colors):
    patch.set_facecolor(color)



ax.set_xticks(np.arange(1, len(labels) + 1))
ax.set_xticklabels(labels, rotation=90, ha='right')

plt.ylabel('Life Expectancy')
plt.xlabel('Year')
plt.title('Life Expectancy by Year')
# show plot
plt.show();

"""The following prompt can be used also for injury, sanitation and communicable disease and life expectancy. But only communicable disease. Based on the correlation matrix, injuries and prevalence of nourishment have the highest correlation (positive and negative) with life expectancy"""

nourish_life = data_drop[['Prevelance of Undernourishment', 'Year', 'Life Expectancy World Bank']].groupby(['Year'])
nourish_life.describe()

nourish_for_boxplot = (data_drop.groupby('Year')['Prevelance of Undernourishment'].agg(list))
nourish_for_boxplot

x = nourish_life['Prevelance of Undernourishment']

data = [x]

# Box plot
fig = plt.figure(figsize =(10, 7))

# Get the labels for the x-axis (carrier codes)
labels = nourish_for_boxplot.index.tolist()

# Convert the Series of lists to a list of arrays for matplotlib boxplot
plot_data = nourish_for_boxplot.values.tolist()

# Create the figure and axes for the box plot
fig, ax = plt.subplots(figsize=(12, 6), dpi=150)

# Create the box plot
bp = ax.boxplot(plot_data, patch_artist=True, vert=True) # vert=True for vertical boxes

# Customize colors for the boxes (optional, but good for visual distinction)
colors = plt.cm.get_cmap('tab10', len(labels)) # Using a colormap for distinct colors
for patch, color in zip(bp['boxes'], colors.colors):
    patch.set_facecolor(color)



ax.set_xticks(np.arange(1, len(labels) + 1))
ax.set_xticklabels(labels, rotation=90, ha='right')

plt.ylabel('Prevelance of Undernourishment')
plt.xlabel('Year')
plt.title('Trend in Prevelance of Undernourishment by Year')
# show plot
plt.show();

injury_life = data_drop[['Injuries', 'Life Expectancy World Bank', 'Year']].groupby(['Year'])
injury_life.describe()

injury_for_boxplot = (data_drop.groupby('Year')['Injuries'].agg(list))
injury_for_boxplot

x = injury_life['Injuries']

data = [x]

# Box plot
fig = plt.figure(figsize =(10, 7))

# Get the labels for the x-axis (carrier codes)
labels = injury_for_boxplot.index.tolist()

# Convert the Series of lists to a list of arrays for matplotlib boxplot
plot_data = injury_for_boxplot.values.tolist()

# Create the figure and axes for the box plot
fig, ax = plt.subplots(figsize=(12, 6), dpi=150)

# Create the box plot
bp = ax.boxplot(plot_data, patch_artist=True, vert=True) # vert=True for vertical boxes

# Customize colors for the boxes (optional, but good for visual distinction)
colors = plt.cm.get_cmap('tab10', len(labels)) # Using a colormap for distinct colors
for patch, color in zip(bp['boxes'], colors.colors):
    patch.set_facecolor(color)



ax.set_xticks(np.arange(1, len(labels) + 1))
ax.set_xticklabels(labels, rotation=90, ha='right')

plt.ylabel('Injuries')
plt.xlabel('Year')
plt.title('Trend in Injuries by Year')
# show plot
plt.show();