# -*- coding: utf-8 -*-
"""MSDS_570_Imputation_for_Predictive_Modelling_SHAP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnlmVXWd1xnR8sGz7ttfHlniVzoftkH5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

# reading data
data = pd.read_csv('/content/drive/MyDrive/life_expectancy.csv')
data.head()

data_drop_corruption = data.copy()
data_drop_corruption.head()

data_drop = data_drop_corruption.drop(columns = 'Corruption')

data_merge_life_expect = data_drop.iloc[:, [2, 4, 5]]
data_merge_life_expect.info()

target_data_nan_life_expect = data_drop.groupby(['Region', 'Year']) ['Life Expectancy World Bank'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_life_expect.info()

data_merge_prevalence_of_under = data_drop.iloc[:, [2, 4, 6]]
data_merge_prevalence_of_under.info()

target_data_nan_prevalence_of_under = data_drop.groupby(['Region', 'Year']) ['Prevelance of Undernourishment'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_prevalence_of_under.info()

data_merge_health_expenditure = data_drop.iloc[:, [2, 4, 8]]
data_merge_health_expenditure.info()

target_data_nan_health_expenditure = data_drop.groupby(['Region', 'Year']) ['Health Expenditure %'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_health_expenditure.info()

data_merge_education_expenditure = data_drop.iloc[:, [2, 4, 9]]
# 1090 nan, contemplating whether filling this nan is even worth it.
data_merge_education_expenditure.info()

target_data_nan_education_expenditure = data_drop.groupby(['Region', 'Year']) ['Education Expenditure %'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_education_expenditure.info()
data_drop['Education Expenditure %'].isna().sum()

# Forward fill ffill()
data_drop['Education Expenditure %'] = data_drop.groupby('Region')['Education Expenditure %'].transform(lambda x: x.sort_values().ffill())

# Backward fill bfill()
data_drop['Education Expenditure %'] = data_drop.groupby('Region')['Education Expenditure %'].transform(lambda x: x.sort_values().bfill())

# Backward fill
#data_drop['Education Expenditure %'].fillna(data_drop['Education Expenditure %'].mean(), inplace=True)

target_data_nan_education_expenditure_updated = data_drop['Education Expenditure %']

target_data_nan_education_expenditure_updated.info()

target_data_nan_education_expenditure.isna().any()

target_data_nan_education_expenditure_updated.isna().any()

data_merge_unemployment = data_drop.iloc[:, [2, 4, 10]]
# similar to the previous column, 1247 nan. Thinking if i should fill this nan
data_merge_unemployment.info()

target_data_nan_unemployment = data_drop.groupby(['Region', 'Year']) ['Unemployment'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_unemployment.info()

data_merge_sanitation = data_drop.iloc[:, [2, 4, 11]]
# similar to the previous column, 1247 nan. Thinking if i should fill this nan
data_merge_sanitation.info()

target_data_nan_sanitation = data_drop.groupby(['Region', 'Year']) ['Sanitation'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_sanitation.info()

data_merge_CO2 = data_drop.iloc[:, [2, 4, 7]]
data_merge_CO2.isna().info()

target_data_nan_CO2 = data_drop.groupby(['Region', 'Year']) ['CO2'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_CO2.info()

data_drop['CO2'] = target_data_nan_CO2
data_drop['Education Expenditure %'] = target_data_nan_education_expenditure_updated
data_drop['Health Expenditure %'] = target_data_nan_health_expenditure
data_drop['Prevelance of Undernourishment'] = target_data_nan_prevalence_of_under
data_drop['Unemployment'] = target_data_nan_unemployment
data_drop['Life Expectancy World Bank'] = target_data_nan_life_expect
data_drop['Sanitation'] = target_data_nan_sanitation

data_drop.info()

data_drop_copy = data_drop.copy()
data_drop_copy.info()

"""# Predictive Modelling"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

longevity_data_predict = data_drop.drop(columns=['Life Expectancy World Bank'])
y = data_drop['Life Expectancy World Bank']

y.info()

longevity_data_predict.info()

longevity_data_predict.isna().any()

longevity_data_num = longevity_data_predict.select_dtypes(exclude=object)
longevity_data_cat = longevity_data_predict.select_dtypes(include=object)

longevity_data_num

longevity_data_num.columns

longevity_data_cat

longevity_data_cat.columns

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(longevity_data_num)

longevity_scaled_data = pd.DataFrame(longevity_data_predict, columns=longevity_data_num.columns)
display(longevity_scaled_data.describe().T)
display(longevity_scaled_data.corr())

longevity_data_catg_dum = pd.DataFrame()
for c in longevity_data_cat.columns:
    dummy = pd.get_dummies(longevity_data_cat[c], prefix=c, dtype=int)
    dummy_sum = dummy.sum(axis=0)
    col_to_drop = dummy_sum.idxmax()
    dummy = dummy.drop(columns=[col_to_drop])
    longevity_data_catg_dum = pd.concat([longevity_data_catg_dum, dummy], axis=1)

longevity_data_catg_dum

longevity_data_catg_dum.columns

longevity_data_catg_dum.info()

longevity_prediction = pd.concat([longevity_scaled_data, longevity_data_catg_dum], axis=1)

! pip install xgboost

import xgboost as xgb
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

models = [
    LinearRegression(),
    KNeighborsRegressor(n_neighbors=1, weights='uniform'),
    KNeighborsRegressor(n_neighbors=10, weights='uniform'),
    KNeighborsRegressor(n_neighbors=100, weights='uniform'),
    DecisionTreeRegressor(max_depth=2),
    DecisionTreeRegressor(max_depth=5),
    DecisionTreeRegressor(max_depth=10),
    RandomForestRegressor(n_estimators=10, max_depth=5),
    RandomForestRegressor(n_estimators=100, max_depth=10),
    GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=2),
    xgb.XGBRegressor(max_depth=2, learning_rate=0.1, n_estimators=100, min_child_weight=5),
]

from sklearn.model_selection import cross_val_score, KFold

kf = KFold(n_splits=5, shuffle=True)

longevity_prediction.columns = longevity_prediction.columns.astype(str) # Convert column names to strings

for m in models:
    print(m)

    cv_scores = -cross_val_score(m, longevity_prediction, y, cv=kf, scoring='neg_mean_absolute_percentage_error')
    cv_scores = pd.DataFrame(cv_scores)
    display(cv_scores.describe().T)

    print()

from sklearn.model_selection import GridSearchCV

# Define models and their parameter grids
param_grids = {
    "KNeighborsRegressor": (
        KNeighborsRegressor(),
        {
            "n_neighbors": [1, 5, 10, 20, 50],
            "weights": ["uniform", "distance"]
        }
    ),

    "RandomForestRegressor": (
        RandomForestRegressor(),
        {
            "n_estimators": [10, 50, 100],
            "max_depth": [3, 5, 10],
            "min_samples_split": [2, 5, 10],
            'min_samples_leaf': [1, 2, 5, 10]
        }
    ),

    "GradientBoostingRegressor": (
        GradientBoostingRegressor(),
        {
            "n_estimators": [50, 100, 200],
            "learning_rate": [0.01, 0.1, 0.2],
            "max_depth": [2, 3, 5],
            'min_samples_leaf': [1, 2, 5, 10]
        }
    ),

    "DecisionTreeRegressor": (
        DecisionTreeRegressor(),
        {
            "max_depth": [2, 3, 5, 10],
            "min_samples_split": [2, 5, 10],
            'min_samples_leaf': [1, 2, 5, 10]
        }
    ),

    "LinearRegression": (
        LinearRegression(),
        {
            "fit_intercept": [True, False],
        }
    ),

    "XGBoost": (
        xgb.XGBRegressor(),
        {
            "n_estimators": [50, 100],
            "learning_rate": [0.01, 0.1, 0.2],
            "max_depth": [2, 3, 5],
            'min_child_weight': [1, 2, 5],
        }
    ),

  }

# Define cross-validation strategy
kf = KFold(n_splits=5, shuffle=True)

longevity_prediction.columns = longevity_prediction.columns.astype(str)

# Store results
results = []

# Perform GridSearchCV for each model
for name, (model, param_grid) in param_grids.items():
    print(f"Performing GridSearchCV for {name}...")

    grid_search = GridSearchCV(model, param_grid, cv=kf, scoring="neg_mean_absolute_percentage_error", n_jobs=-1)
    grid_search.fit(longevity_prediction, y)

    best_params = grid_search.best_params_
    best_score = grid_search.best_score_

    results.append({"Model": name, "Best Score": best_score, "Best Params": best_params})


results

# Fit a Random Forest model
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(longevity_prediction, y)

# Get feature importances
importances = pd.Series(rf.feature_importances_, index=longevity_prediction.columns).sort_values(ascending=False)
importances = importances[:20]

features_rf = importances.index

longevity_prediction_pars = longevity_prediction[ features_rf ]
importances

! pip install statsmodels

from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

longevity_prediction_pars_with_const = sm.add_constant(longevity_prediction_pars)

vif = pd.Series(
    [variance_inflation_factor(longevity_prediction_pars_with_const.values, i) for i in range(longevity_prediction_pars_with_const.shape[1])],
    index=longevity_prediction_pars_with_const.columns
).sort_values(ascending=False)

vif[:20]

longevity_prediction_vif = longevity_prediction_pars.copy()
while True:
  longevity_prediction_vif_with_const = sm.add_constant(longevity_prediction_vif)

  # Compute VIF for all features
  vif_series = pd.Series(
  [variance_inflation_factor(longevity_prediction_vif_with_const.values, i) for i in range(longevity_prediction_vif_with_const.shape[1])],
  index=longevity_prediction_vif_with_const.columns
    )
  #Exclude constant term
  vif_series = vif_series.drop('const', errors='ignore')
  highest_vif_feature = vif_series.idxmax()
  # Break the loop if all features have VIF ≤ 10
  if vif_series.loc[highest_vif_feature] <= 6:  # Checking the first feature after 'const'
    break

  # Drop the feature with the highest VIF
  longevity_prediction_vif = longevity_prediction_vif.drop(columns=[highest_vif_feature])

  print(f"Dropped: {highest_vif_feature} (VIF={vif_series.loc[highest_vif_feature]:.2f})")
  # end


vif_series[:25]

from sklearn.model_selection import GridSearchCV

# Define models and their parameter grids
param_grids = {
    "KNeighborsRegressor": (
        KNeighborsRegressor(),
        {
            "n_neighbors": [1, 5, 10, 20, 50],
            "weights": ["uniform", "distance"]
        }
    ),

    "RandomForestRegressor": (
        RandomForestRegressor(),
        {
            "n_estimators": [10, 50, 100],
            "max_depth": [3, 5, 10],
            "min_samples_split": [2, 5, 10],
            'min_samples_leaf': [1, 2, 5, 10]
        }
    ),

    "GradientBoostingRegressor": (
        GradientBoostingRegressor(),
        {
            "n_estimators": [50, 100, 200],
            "learning_rate": [0.01, 0.1, 0.2],
            "max_depth": [2, 3, 5],
            'min_samples_leaf': [1, 2, 5, 10]
        }
    ),

    "DecisionTreeRegressor": (
        DecisionTreeRegressor(),
        {
            "max_depth": [2, 3, 5, 10],
            "min_samples_split": [2, 5, 10],
            'min_samples_leaf': [1, 2, 5, 10]
        }
    ),

    "LinearRegression": (
        LinearRegression(),
        {
            "fit_intercept": [True, False],
        }
    ),

      "XGBoost": (
        xgb.XGBRegressor(),
        {
            "n_estimators": [50, 100],
            "learning_rate": [0.01, 0.1, 0.2],
            "max_depth": [2, 3, 5],
            'min_child_weight': [1, 2, 5],
        }
    ),

  }

# Define cross-validation strategy
kf = KFold(n_splits=5, shuffle=True)

longevity_prediction.columns = longevity_prediction.columns.astype(str) # Convert column names to strings

# Store results
results = []

# Perform GridSearchCV for each model
for name, (model, param_grid) in param_grids.items():
    print(f"Performing GridSearchCV for {name}...")

    grid_search = GridSearchCV(model, param_grid, cv=kf, scoring="neg_mean_absolute_percentage_error", n_jobs=-1)
    grid_search.fit(longevity_prediction_vif, y)

    best_params = grid_search.best_params_
    best_score = grid_search.best_score_

    results.append({"Model": name, "Best Score": best_score, "Best Params": best_params})
# end

results

! pip install tensorflow --upgrade

! pip install keras --upgrade

from keras.models import Sequential
from keras.layers import *
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.schedules import ExponentialDecay, PolynomialDecay
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

def build_model( longevity_prediction_train, epochs, batch_size, decay_frac, initial_learning_rate, dropout_rate ):

    # Create model
    model = Sequential([
        Input(shape=longevity_prediction_train.shape[1]),
        Dense(128, activation='relu'),
        Dropout(dropout_rate),
        Dense(64, activation='relu'),
        Dropout(dropout_rate),
        Dense(256, activation='relu'),
        Dense(1, activation='relu'),
    ])

    # define training parameters
    decay_epochs    = int( epochs * decay_frac )
    n_train         = longevity_prediction_train.shape[0]
    steps_per_epoch = int( np.ceil( n_train / batch_size ) )
    decay_steps     = decay_epochs * steps_per_epoch

    lr_schedule_poly = PolynomialDecay(
        initial_learning_rate=initial_learning_rate,
        end_learning_rate=0.001,
        decay_steps=decay_steps,
        power=2.0
    )

    # Define the optimizer with a custom learning rate
    optimizer = Adam(
        learning_rate=lr_schedule_poly,
    )

    # Compile model
    model.compile(
        optimizer=optimizer,
        loss='mae'
    )

    return model

from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, r2_score

# Re-defining build_model with the fix for the Input layer
from keras.models import Sequential
from keras.layers import *
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.schedules import ExponentialDecay, PolynomialDecay
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

def build_model( longevity_prediction_train, epochs, batch_size, decay_frac, initial_learning_rate, dropout_rate ):

    # Create model
    model = Sequential([
        Input(shape=(longevity_prediction_train.shape[1],)),
        Dense(128, activation='relu'),
        Dropout(dropout_rate),
        Dense(64, activation='relu'),
        Dropout(dropout_rate),
        Dense(256, activation='relu'),
        Dense(1, activation='relu'),
    ])

    # define training parameters
    decay_epochs    = int( epochs * decay_frac )
    n_train         = longevity_prediction_train.shape[0]
    steps_per_epoch = int( np.ceil( n_train / batch_size ) )
    decay_steps     = decay_epochs * steps_per_epoch

    lr_schedule_poly = PolynomialDecay(
        initial_learning_rate=initial_learning_rate,
        end_learning_rate=0.001,
        decay_steps=decay_steps,
        power=2.0
    )

    # Define the optimizer with a custom learning rate
    optimizer = Adam(
        learning_rate=lr_schedule_poly,
    )

    # Compile model
    model.compile(
        optimizer=optimizer,
        loss='mae'
    )

    return model
# end

epochs                = 500
batch_size            = 256
decay_frac            = 0.8
dropout_rate          = 0.1
initial_learning_rate = 0.01

n_splits = 5
kf = KFold(n_splits=n_splits, shuffle=True)

train_mae_list = []
test_mae_list = []
train_r2_list = []
test_r2_list = []

fold = 1
for train_index, test_index in kf.split(longevity_prediction):
    print(f"Fold {fold}/{n_splits}")
    longevity_prediction_train, longevity_prediction_test = longevity_prediction.iloc[train_index], longevity_prediction.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Build a fresh model (which resets optimizer state including the learning rate schedule)
    model = build_model(
        longevity_prediction_train,
        epochs,
        batch_size,
        decay_frac,
        initial_learning_rate,
        dropout_rate
    )

    # Early stopping callback
    early_stopping = EarlyStopping(
        monitor='val_loss',  # Monitor validation loss
        patience=100,          # Stop after 5 epochs without improvement
        restore_best_weights=True  # Restore the best weights after stopping
    )

    # Train the model both x and y
    history = model.fit(
        longevity_prediction_train, y_train,
        epochs=epochs,
        batch_size=batch_size,
        validation_data=(longevity_prediction_test, y_test),
        verbose=0,
        callbacks=[early_stopping]
    )

    # Evaluate on training data
    y_train_pred = model.predict(longevity_prediction_train, verbose=0)
    train_mae = mean_absolute_error(y_train, y_train_pred)
    train_r2 = r2_score(y_train, y_train_pred)

    # Evaluate on test data
    y_test_pred = model.predict(longevity_prediction_test, verbose=0)
    test_mae = mean_absolute_error(y_test, y_test_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    print("MAE:")
    print(f"  Train: {train_mae:.4f}")
    print(f"  Test:  {test_mae:.4f}")
    print("R^2:")
    print(f"  Train: {train_r2:.4f}")
    print(f"  Test:  {test_r2:.4f}")
    print()

    train_mae_list.append(train_mae)
    test_mae_list.append(test_mae)
    train_r2_list.append(train_r2)
    test_r2_list.append(test_r2)

    fold += 1
# end

cross_validation_result_df = pd.DataFrame({
    'Train MAE': train_mae_list,
    'Test MAE': test_mae_list,
    'Train R2': train_r2_list,
    'Test R2': test_r2_list
})

cross_validation_result_df.describe()

from sklearn.model_selection import train_test_split

longevity_prediction_train, longevity_prediciton_test, y_train, y_test = train_test_split(longevity_prediction_vif, y,
                                                    test_size=0.2)

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

# Define the number of attempts
attempts = 1000

# Determine the global min and max of y
y_min, y_max = y.min(), y.max()
bins = np.linspace(y_min, y_max, 25)  # 25 bins means 26 edges

best_mse = float('inf')
best_split = None

for i in range(attempts):
    # Perform train-test split
    longevity_prediction_train_i, longevity_prediction_test_i, y_train_i, y_test_i = train_test_split(longevity_prediction_vif, y, test_size=0.2)

    # Compute histograms
    y_train_hist, _ = np.histogram(y_train_i, bins=bins, density=True)
    y_test_hist, _ = np.histogram(y_test_i, bins=bins, density=True)

    # Compute MSE between histograms
    mse = mean_squared_error(y_train_hist, y_test_hist)

    # Save the best split
    if mse < best_mse:
        best_mse = mse
        best_split = (longevity_prediction_train_i, longevity_prediction_test_i, y_train_i, y_test_i)

# Unpack the best split
longevity_prediction_train, longevity_prediction_test, y_train, y_test = best_split

# Display histograms of the best split
plt.hist(y_train, bins=bins, alpha=0.5, color='b', label='Train', density=True)
plt.hist(y_test, bins=bins, alpha=0.3, color='r', label='Test', density=True)
plt.legend()
plt.xlabel('y values')
plt.ylabel('Density')
plt.title('Best Train-Test Split Histogram Comparison')
plt.show()

from keras.models import Sequential
from keras.layers import *
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

dropout_rate = 0.05 #I changed dropout rate from 0.05 to 0.01 used to prevent overfitting

# Create model complexity
model = Sequential([
    Input(shape=(longevity_prediction_train.shape[1],)),
    Dense(64, activation='relu'), # originally 32 neurons
    BatchNormalization(),
    Dropout(dropout_rate),
    Dense(128, activation='relu'), # originally 64 neurons
    BatchNormalization(),
    Dropout(dropout_rate),
    Dense(32, activation='relu'), #originally 128 neurons
    Dense(1, activation='relu'),
])

# Define the optimizer with a custom learning rate
optimizer = Adam(learning_rate=0.01)

# Compile model
model.compile(
    optimizer=optimizer,
    loss='mae'
)

# Early stopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',  # Monitor validation loss
    patience=100,          # Stop after 5 epochs without improvement, changed from 100 to 50
    restore_best_weights=True  # Restore the best weights after stopping
)

# Display model summary
model.summary()

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.schedules import ExponentialDecay, PolynomialDecay

# define training parameters
epochs          = 500 # Originally 500
batch_size      = 256
decay_epochs    = int( epochs * 0.5 )

n_train         = longevity_prediction_train.shape[0]
steps_per_epoch = int( np.ceil( n_train / batch_size ) )
decay_steps     = decay_epochs * steps_per_epoch
#print(decay_steps)

# Define the learning rate schedule
initial_learning_rate = 0.05

lr_schedule_exp = ExponentialDecay(
    initial_learning_rate=initial_learning_rate,
    decay_rate=5.0,
    decay_steps=decay_steps
)

lr_schedule_poly = PolynomialDecay(
    initial_learning_rate=initial_learning_rate,
    end_learning_rate=0.001,
    decay_steps=decay_steps,
    power=1.0
)

# Define the optimizer with a custom learning rate
optimizer = Adam(
    learning_rate=initial_learning_rate,
    #learning_rate=lr_schedule_exp,
    #learning_rate=lr_schedule_poly,
    #clipnorm=1,
    #clipvalue=1,
)

# Compile model
model.compile(
    optimizer=optimizer,
    loss='mae'
)

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Early stopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',  # Monitor validation loss
    patience=30,          # Stop after 50 epochs without improvement
    restore_best_weights=True  # Restore the best weights after stopping
)

# Callback to reduce LR when a monitored metric has stopped improving
reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',       # metric to monitor
    factor=0.5,               # factor by which to reduce the LR
    patience=30,              # number of epochs with no improvement after which LR will be reduced, changed from 50 to 40
    min_lr=1e-6,              # lower bound on the learning rate
    verbose=1                 # print when LR is reduced
)

# Train model
history = model.fit(
    longevity_prediction_train, y_train,
    epochs=400, #originally at 400
    batch_size=batch_size,
    shuffle=True,
    validation_data=(longevity_prediciton_test, y_test),
    verbose=1,
    callbacks=[
        early_stopping,
    ]
)

from sklearn.metrics import mean_absolute_error, r2_score

# Get predictions
y_train_pred = model.predict(longevity_prediction_train)[:,0]
y_test_pred  = model.predict(longevity_prediction_test)[:,0]

# Create a figure with two subplots side by side
fig, axes = plt.subplots(1, 2, figsize=(20, 8))

# Left subplot: Training and Validation Loss
axes[0].plot(history.history['loss'], label='Training Loss')
axes[0].plot(history.history['val_loss'], label='Validation Loss')
axes[0].set_yscale('log')
axes[0].set_title('Training and Validation Loss')
axes[0].set_xlabel('Epochs')
axes[0].set_ylabel('Loss')
axes[0].legend()

# Right subplot: True vs Predicted Data
axes[1].scatter(y_train, y_train_pred, c='b', s=1, label="Train set")
axes[1].scatter(y_test, y_test_pred, c='r', s=1, label="Test set")
axes[1].set_title('True vs Pred (test data)')
axes[1].set_xlabel('true')
axes[1].set_ylabel('pred')
axes[1].legend()

plt.tight_layout()
plt.show()

mae_train = mean_absolute_error(y_train, y_train_pred)
r2_train = r2_score(y_train, y_train_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)
r2_test = r2_score(y_test, y_test_pred)

print("MAE:")
print(f"  Train: {mae_train:.4f}")
print(f"  Test:  {mae_test:.4f}")
print("R^2:")
print(f"  Train: {r2_train:.4f}")
print(f"  Test:  {r2_test:.4f}")

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, r2_score

# Define regression models corresponding to the original classifiers
models = [
    LinearRegression(),
    KNeighborsRegressor(n_neighbors=5, weights='uniform'),
    KNeighborsRegressor(n_neighbors=10, weights='uniform'),
    KNeighborsRegressor(n_neighbors=50, weights='uniform'),
    RandomForestRegressor(n_estimators=100, max_leaf_nodes=3),
    RandomForestRegressor(n_estimators=100, max_leaf_nodes=10),
    RandomForestRegressor(n_estimators=100, max_leaf_nodes=30),
    GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_leaf_nodes=3),
    GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_leaf_nodes=10),
    DecisionTreeRegressor(max_leaf_nodes=3),
    DecisionTreeRegressor(max_leaf_nodes=10),
    xgb.XGBRegressor(max_depth=2, learning_rate=0.1, n_estimators=100, min_child_weight=5),
]

for m in models:
    m.fit(longevity_prediction_train, y_train)
    y_train_pred = m.predict(longevity_prediction_train)
    y_test_pred = m.predict(longevity_prediction_test)

    # Compute regression metrics
    mae_train = mean_absolute_error(y_train, y_train_pred)
    r2_train = r2_score(y_train, y_train_pred)
    mae_test = mean_absolute_error(y_test, y_test_pred)
    r2_test = r2_score(y_test, y_test_pred)

    # Print model and its metrics
    print(m)
    print("MAE:")
    print(f"  Train: {mae_train:.4f}")
    print(f"  Test:  {mae_test:.4f}")
    print("R^2:")
    print(f"  Train: {r2_train:.4f}")
    print(f"  Test:  {r2_test:.4f}")
    print()
# end

# Create a DataFrame to organize the data of true vs pred data graph of a R of 0.83 which is a bit low
predicted_results_df = pd.DataFrame({
    'Actual Life Expectancy': y_test,
    'Predicted Life Expectancy': y_test_pred,
    'Difference (Error)': (y_test - y_test_pred),
    'Percentage Error (%)': ((abs(y_test - y_test_pred) / y_test) * 100)
})

# Get the original 'Country Name' and 'Year' directly from data_drop using y_test's index
country_year_info = data_drop.loc[y_test.index, ['Country Name', 'Year']]

# Merge this information into predicted_results_df, aligning by index
predicted_results_df = predicted_results_df.merge(country_year_info, left_index=True, right_index=True)

# Reorder columns to have Country Name and Year at the beginning for clarity
predicted_results_df = predicted_results_df[[
    'Country Name', 'Year', 'Actual Life Expectancy', 'Predicted Life Expectancy',
    'Difference (Error)', 'Percentage Error (%)'
]]

# Display the resulting numerical table without explicit sorting, showing the split order
predicted_results_df

predicted_results_df.info()

# Filter predicted_results_df for 'Countries' to see all its entries in the test set
countries_predictions_corrected = predicted_results_df[predicted_results_df['Country Name'] == 'Germany'].sort_values(by='Year')
print("Country entries in the corrected predicted_results_df (from original csv dataset):")
display(countries_predictions_corrected)

# Display the specific entry for Countries in 2014 from the original data_drop
print("\nLife Expectancy for random country in 2014 from original data_drop:")
display(data_drop[(data_drop['Country Name'] == 'Germany') & (data_drop['Year'] == 2016)])

# Display all data_drop entries with Life Expectancy around 45.100
print("\nAll data_drop entries with Life Expectancy around 45.100:")
display(data_drop[data_drop['Life Expectancy World Bank'].between(45.0, 45.2)])

# Get the original indices from y_test (which was used to create predicted_results_df)
original_indices = y_test.index

# Map these indices back to data_drop to get the 'Country Name'
country_names_for_test_set = data_drop.loc[original_indices, 'Country Name']

# Add 'Country Name' to the predicted_results_df
predicted_results_df['Country Name'] = country_names_for_test_set.values

predicted_results_df = predicted_results_df[['Country Name', 'Year','Actual Life Expectancy', 'Predicted Life Expectancy', 'Difference (Error)', 'Percentage Error (%)']]

# Display the updated DataFrame
display(predicted_results_df.head())

! pip install shap

import shap

from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(longevity_prediction_train, y_train)

# 2. Incorporate SHAP (No re-training needed)
import shap
explainer = shap.Explainer(m, longevity_prediction_train) # It just looks at your existing 'model'
shap_values = explainer(longevity_prediction_test)

# 3. Visualize
shap.plots.waterfall(shap_values[0])

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor().fit(longevity_prediction_train, y_train)

# 2. Incorporate SHAP (No re-training needed)
import shap
explainer = shap.Explainer(m, longevity_prediction_train) # It just looks at your existing 'model'
shap_values = explainer(longevity_prediction_test)

# 3. Visualize
shap.plots.waterfall(shap_values[0])

import shap

explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(longevity_prediction_test)

shap.summary_plot(shap_values, longevity_prediction_test)

import shap
explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(longevity_prediction_test)

shap.decision_plot(explainer.expected_value, shap_values, longevity_prediction_test)