# -*- coding: utf-8 -*-
"""MSDS_570_Imputation_for_Correlogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFjDRPOMCGrfp7vf3oknNc2TjBTBZZ9z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

# reading data
data = pd.read_csv('/content/drive/MyDrive/life_expectancy.csv')
data.head()

data_drop_corruption = data.copy()
data_drop_corruption.head()

data_drop = data_drop_corruption.drop(columns = 'Corruption')

data_merge_life_expect = data_drop.iloc[:, [2, 4, 5]]
data_merge_life_expect.info()

target_data_nan_life_expect = data_drop.groupby(['Region', 'Year']) ['Life Expectancy World Bank'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_life_expect.info()

data_merge_prevalence_of_under = data_drop.iloc[:, [2, 4, 6]]
data_merge_prevalence_of_under.info()

target_data_nan_prevalence_of_under = data_drop.groupby(['Region', 'Year']) ['Prevelance of Undernourishment'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_prevalence_of_under.info()

data_merge_health_expenditure = data_drop.iloc[:, [2, 4, 8]]
data_merge_health_expenditure.info()

target_data_nan_health_expenditure = data_drop.groupby(['Region', 'Year']) ['Health Expenditure %'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_health_expenditure.info()

data_merge_education_expenditure = data_drop.iloc[:, [2, 4, 9]]
# 1090 nan, contemplating whether filling this nan is even worth it.
data_merge_education_expenditure.info()

target_data_nan_education_expenditure = data_drop.groupby(['Region', 'Year']) ['Education Expenditure %'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_education_expenditure.info()
data_drop['Education Expenditure %'].isna().sum()

# Forward fill ffill()
data_drop['Education Expenditure %'] = data_drop.groupby('Region')['Education Expenditure %'].transform(lambda x: x.sort_values().ffill())

# Backward fill bfill()
data_drop['Education Expenditure %'] = data_drop.groupby('Region')['Education Expenditure %'].transform(lambda x: x.sort_values().bfill())

# Backward fill
#data_drop['Education Expenditure %'].fillna(data_drop['Education Expenditure %'].mean(), inplace=True)

target_data_nan_education_expenditure_updated = data_drop['Education Expenditure %']

target_data_nan_education_expenditure_updated.info()

target_data_nan_education_expenditure.isna().any()

target_data_nan_education_expenditure_updated.isna().any()

data_merge_unemployment = data_drop.iloc[:, [2, 4, 10]]
# similar to the previous column, 1247 nan. Thinking if i should fill this nan
data_merge_unemployment.info()

target_data_nan_unemployment = data_drop.groupby(['Region', 'Year']) ['Unemployment'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_unemployment.info()

data_merge_sanitation = data_drop.iloc[:, [2, 4, 11]]
# similar to the previous column, 1247 nan. Thinking if i should fill this nan
data_merge_sanitation.info()

target_data_nan_sanitation = data_drop.groupby(['Region', 'Year']) ['Sanitation'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_sanitation.info()

data_merge_CO2 = data_drop.iloc[:, [2, 4, 7]]
data_merge_CO2.isna().info()

target_data_nan_CO2 = data_drop.groupby(['Region', 'Year']) ['CO2'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_CO2.info()

data_drop['CO2'] = target_data_nan_CO2
data_drop['Education Expenditure %'] = target_data_nan_education_expenditure_updated
data_drop['Health Expenditure %'] = target_data_nan_health_expenditure
data_drop['Prevelance of Undernourishment'] = target_data_nan_prevalence_of_under
data_drop['Unemployment'] = target_data_nan_unemployment
data_drop['Life Expectancy World Bank'] = target_data_nan_life_expect
data_drop['Sanitation'] = target_data_nan_sanitation

data_drop.info()

data_drop_copy = data_drop.copy()
data_drop_copy.info()

corr = data_drop_copy.select_dtypes(exclude=object).corr()
print(display(corr))

plt.figure(figsize=(10,8))
sns.heatmap(
    corr,
    vmin=-1,
    vmax=1,
    cmap='bwr'
)
#plt.xticks(rotation=90, ha='right', rotation_mode='anchor', annot=True, annot_kws={"size": 6});
sns.heatmap(corr, annot=True, cmap='bwr')
plt.show()

income_class_global = data_drop_copy.iloc[:, [2,5]]
income_class_global.info()

catg_heat_map_function = income_class_global[income_class_global['Region'] == 'South Asia'][['Life Expectancy World Bank']]
catg_heat_map_function

catg_heat_map_function.shape

# Calculate the mean Life Expectancy World Bank for each Region
regional_life_expectancy = income_class_global.groupby('Region')['Life Expectancy World Bank'].mean().reset_index()

# Set 'Region' as the index for plotting
regional_life_expectancy = regional_life_expectancy.set_index('Region')

regional_life_expectancy

plt.figure(figsize=(10, 8)) # Adjust figure size as needed
sns.heatmap(regional_life_expectancy, annot=True, cmap='bwr', fmt=".1f", linewidths=.5)
plt.title('Average Life Expectancy World Bank by Region')
plt.xlabel('') # No x-label needed for single column
plt.ylabel('Region')
plt.yticks(rotation=0) # Ensure y-labels are readable
plt.show()

year_class_global = data_drop_copy.iloc[:, [4,5]]
year_class_global.info()

year_heat_map_function = year_class_global[year_class_global['Year'] == 2017][['Life Expectancy World Bank']]
year_heat_map_function.info()

# Calculate the mean Life Expectancy World Bank for each Year
year_life_expectancy = year_class_global.groupby('Year')['Life Expectancy World Bank'].mean()

# The result is already a Series with Year as the index

year_life_expectancy

plt.figure(figsize=(15, 2)) # Adjust figure size for a horizontal heatmap
sns.heatmap(year_life_expectancy.to_frame().T, annot=True, cmap='bwr', fmt=".1f", linewidths=.5)
plt.title('Average Life Expectancy World Bank Over the Years')
plt.xlabel('Year') # Label for years as columns
plt.ylabel('') # Hide y-label as there's only one row (Life Expectancy)
plt.yticks([]) # Ensure y-labels are hidden
plt.show()

# Define the year you want to visualize
selected_year = 2016 # You can change this to any year between 2001 and 2019

# Filter the data for the selected year
data_for_selected_year = data_drop_copy[data_drop_copy['Year'] == selected_year]

# Calculate the mean Life Expectancy World Bank for each Region in the selected year
yearly_regional_life_expectancy = data_for_selected_year.groupby('Region')['Life Expectancy World Bank'].mean().reset_index()

# Set 'Region' as the index for plotting
yearly_regional_life_expectancy = yearly_regional_life_expectancy.set_index('Region')

yearly_regional_life_expectancy

plt.figure(figsize=(10, 8)) # Adjust figure size as needed
sns.heatmap(yearly_regional_life_expectancy, annot=True, cmap='bwr', fmt=".1f", linewidths=.5)
plt.title(f'Average Life Expectancy World Bank by Region in {selected_year}')
plt.xlabel('') # No x-label needed for single column
plt.ylabel('Region')
plt.yticks(rotation=0) # Ensure y-labels are readable
plt.show()

