# -*- coding: utf-8 -*-
"""MSDS_570_Imputation_for_GeoMap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZAiWHP20Qq6EQiuTxbWmS1cMkU7fj6F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

# reading data
data = pd.read_csv('/content/drive/MyDrive/life_expectancy.csv')
data.head()

data_drop_corruption = data.copy()
data_drop_corruption.head()

data_drop = data_drop_corruption.drop(columns = 'Corruption')

data_merge_life_expect = data_drop.iloc[:, [2, 4, 5]]
data_merge_life_expect.info()

target_data_nan_life_expect = data_drop.groupby(['Region', 'Year']) ['Life Expectancy World Bank'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_life_expect.info()

data_merge_prevalence_of_under = data_drop.iloc[:, [2, 4, 6]]
data_merge_prevalence_of_under.info()

target_data_nan_prevalence_of_under = data_drop.groupby(['Region', 'Year']) ['Prevelance of Undernourishment'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_prevalence_of_under.info()

data_merge_health_expenditure = data_drop.iloc[:, [2, 4, 8]]
data_merge_health_expenditure.info()

target_data_nan_health_expenditure = data_drop.groupby(['Region', 'Year']) ['Health Expenditure %'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_health_expenditure.info()

data_merge_education_expenditure = data_drop.iloc[:, [2, 4, 9]]
# 1090 nan, contemplating whether filling this nan is even worth it.
data_merge_education_expenditure.info()

target_data_nan_education_expenditure = data_drop.groupby(['Region', 'Year']) ['Education Expenditure %'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_education_expenditure.info()
data_drop['Education Expenditure %'].isna().sum()

# Forward fill ffill()
data_drop['Education Expenditure %'] = data_drop.groupby('Region')['Education Expenditure %'].transform(lambda x: x.sort_values().ffill())

# Backward fill bfill()
data_drop['Education Expenditure %'] = data_drop.groupby('Region')['Education Expenditure %'].transform(lambda x: x.sort_values().bfill())

# Backward fill
#data_drop['Education Expenditure %'].fillna(data_drop['Education Expenditure %'].mean(), inplace=True)

target_data_nan_education_expenditure_updated = data_drop['Education Expenditure %']

target_data_nan_education_expenditure_updated.info()

target_data_nan_education_expenditure.isna().any()

target_data_nan_education_expenditure_updated.isna().any()

data_merge_unemployment = data_drop.iloc[:, [2, 4, 10]]
# similar to the previous column, 1247 nan. Thinking if i should fill this nan
data_merge_unemployment.info()

target_data_nan_unemployment = data_drop.groupby(['Region', 'Year']) ['Unemployment'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_unemployment.info()

data_merge_sanitation = data_drop.iloc[:, [2, 4, 11]]
# similar to the previous column, 1247 nan. Thinking if i should fill this nan
data_merge_sanitation.info()

target_data_nan_sanitation = data_drop.groupby(['Region', 'Year']) ['Sanitation'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_sanitation.info()

data_merge_CO2 = data_drop.iloc[:, [2, 4, 7]]
data_merge_CO2.isna().info()

target_data_nan_CO2 = data_drop.groupby(['Region', 'Year']) ['CO2'].transform(lambda x: x.fillna(x.mean()))

target_data_nan_CO2.info()

data_drop['CO2'] = target_data_nan_CO2
data_drop['Education Expenditure %'] = target_data_nan_education_expenditure_updated
data_drop['Health Expenditure %'] = target_data_nan_health_expenditure
data_drop['Prevelance of Undernourishment'] = target_data_nan_prevalence_of_under
data_drop['Unemployment'] = target_data_nan_unemployment
data_drop['Life Expectancy World Bank'] = target_data_nan_life_expect
data_drop['Sanitation'] = target_data_nan_sanitation

data_drop.info()

!pip install geopandas
!pip install geoplot
!pip install folium

# Commented out IPython magic to ensure Python compatibility.
import folium
import geopandas as gpd
import geoplot
import geoplot.crs as gcrs
import matplotlib.pyplot as plt
# %matplotlib inline

df_temp = pd.DataFrame(data_drop)
df_temp.to_csv('longevity.csv', index=False)
csv_file_path = 'longevity.csv'

# 1. Read the CSV using pandas
longevity_df = pd.read_csv(csv_file_path)
display(longevity_df.head())

# Replace 'Your_Country_Column_Name' and 'Your_Life_Expectancy_Column_Name' with your actual column names
country_life_expectancy_data = longevity_df[['Country Name', 'Life Expectancy World Bank']]#.copy()

# Rename columns to 'Country' and 'Value' to match the subsequent merge logic
#country_life_expectancy_data.columns = ['Country', 'Value']

print("Extracted data")
display(country_life_expectancy_data.head())
#country_life_expectancy_data.info()

from google.colab import files
import os

# Upload the shapefile and all its companion files (e.g., .dbf, .shx, .prj)
print("Please upload your shapefile (.shp, .shx, .dbf, .prj, etc.) files.")
uploaded = files.upload()

# Assuming all uploaded files are in the current working directory
# We need to find the .shp file among them.
shp_file_name = None
for name, data in uploaded.items():
    if name.endswith('.shp'):
        shp_file_name = name
        print(f"Found shapefile: {shp_file_name}")
        break

if shp_file_name is None:
    print("Error: No .shp file was uploaded.")
else:
    # Define the path to the uploaded shapefile
    # In Colab, uploaded files are typically in the root directory or can be accessed directly by name.
    global_shp_file_path = os.path.join(os.getcwd(), shp_file_name)
    print(f"Global shapefile path set to: {global_shp_file_path}")

# Now, the 'global_shp_file_path' variable can be used in the choropleth map code

import geopandas as gpd
import folium
import os

# Load the shapefile directly from the local path
world_gdf = gpd.read_file(global_shp_file_path)

# --- DEBUG: Print columns to find correct country name field ---
print("Columns in world_gdf:")
print(world_gdf.columns)
# ---------------------------------------------------------------

# Aggregate longevity_df to get one life expectancy value per country
# We'll use the mean life expectancy across all years for each country
mean_life_expectancy_per_country = longevity_df.groupby('Country Name')['Life Expectancy World Bank'].mean().reset_index()

# The current shapefile does not contain a country name column to merge on.
# We need a shapefile with a country name attribute (e.g., 'NAME', 'COUNTRY', 'ADMIN').
# Please upload or specify a different shapefile that includes country name information.

# Removed the merging and plotting code as it would fail without the country name column.
# You can re-enable this once a suitable shapefile is provided.
# merged_gdf = world_gdf.merge(mean_life_expectancy_per_country,
#                              left_on='NAME', right_on='Country Name', how='left')

# m = folium.Map(location=[0, 0], zoom_start=2)

# folium.Choropleth(
#     geo_data=merged_gdf,
#     name='choropleth',
#     data=merged_gdf,
#     columns=['NAME', 'Life Expectancy World Bank'],
#     key_on='feature.properties.NAME',
#     fill_color='YlGnBu',
#     fill_opacity=0.7,
#     line_opacity=0.2,
#     legend_name='Global Life Expectancy'
# ).add_to(m)

# folium.LayerControl().add_to(m)

# display(m)

import geopandas as gpd
import folium
import os
from google.colab import files

# Assuming files are already uploaded in a previous step, and 'uploaded' dict is available.
# If not, you'd need to run files.upload() here again.

# First, identify the base name of the SHP file that was actually used.
# From previous output, it was 'ne_110m_admin_0_countries (3).shp'
shp_file_name_uploaded = 'ne_110m_admin_0_countries (3).shp'
base_name = os.path.splitext(shp_file_name_uploaded)[0]

# List of expected extensions for a shapefile
extensions = ['.shp', '.dbf', '.shx', '.prj', '.cpg']

# Rename files to ensure consistent base name
for ext in extensions:
    original_name = base_name.replace(' (3)', '') + ext # Try original name without (3)
    new_name = base_name + ext # Target name with (3)

    if os.path.exists(original_name) and not os.path.exists(new_name):
        os.rename(original_name, new_name)
        print(f"Renamed '{original_name}' to '{new_name}'")

# Define the path to the corrected shapefile
global_shp_file_path = os.path.join(os.getcwd(), shp_file_name_uploaded)
print(f"Using shapefile path: {global_shp_file_path}")

# Load the shapefile with the corrected names
world_gdf = gpd.read_file(global_shp_file_path)

# --- DEBUG: Print columns to confirm correct country name field ---
print("\nColumns in world_gdf after loading with corrected filenames:")
print(world_gdf.columns)

# Aggregate longevity_df to get one life expectancy value per country
mean_life_expectancy_per_country = longevity_df.groupby('Country Name')['Life Expectancy World Bank'].mean().reset_index()

# Merge the world GeoDataFrame with your life expectancy data
# Assuming 'NAME' in world_gdf corresponds to 'Country Name' in your data
merged_gdf = world_gdf.merge(
    mean_life_expectancy_per_country,
    left_on='NAME', # Often 'NAME' or 'name_long' is the country name column in these shapefiles
    right_on='Country Name',
    how='left'
)

# --- DEBUG: Check merged data ---
print("\nMerged GeoDataFrame. Showing relevant columns for mapping:")
display(merged_gdf[['NAME', 'Country Name', 'Life Expectancy World Bank', 'geometry']].head())

# Create a Folium map
m = folium.Map(location=[0, 0], zoom_start=2)

# Add the choropleth layer
folium.Choropleth(
    geo_data=merged_gdf,
    name='choropleth',
    data=merged_gdf,
    columns=['NAME', 'Life Expectancy World Bank'],
    key_on='feature.properties.NAME',
    fill_color='YlGnBu',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Global Life Expectancy'
).add_to(m)

# Add layer control to toggle choropleth on/off
folium.LayerControl().add_to(m)

# Display the map
display(m)

fixing_longevity_df = pd.read_csv('longevity.csv')
fixing_longevity_df.info()

chloropleth_map = fixing_longevity_df.iloc[:, [0, 5]]
chloropleth_map.info()

chloropleth_map['Country Name'].unique()

# Create a copy of the original longevity_df to work with
longevity_df_corrected = longevity_df.copy()

# Display the head of the new DataFrame to confirm
display(longevity_df_corrected.tail(10))

# UPDATED CODE - 2024-07-29 13:10:00

import geopandas as gpd
import os

# Reload world_gdf for direct comparison in this cell (assuming global_shp_file_path is set)
shp_file_name_uploaded = 'ne_110m_admin_0_countries (3).shp'
global_shp_file_path = os.path.join(os.getcwd(), shp_file_name_uploaded)
world_gdf = gpd.read_file(global_shp_file_path)

# Identify the correct country name column in world_gdf (assuming 'NAME' based on previous checks)
merge_column_name_gdf = 'NAME'
if merge_column_name_gdf not in world_gdf.columns:
    print(f"Warning: '{merge_column_name_gdf}' not found in world_gdf. Attempting to find another... ")
    for col in ['ADMIN', 'sovereignt', 'name_long']:
        if col in world_gdf.columns:
            merge_column_name_gdf = col
            print(f"Using '{merge_column_name_gdf}' as merge column in world_gdf.")
            break
    else:
        raise ValueError("Could not find a suitable country name column in world_gdf.")

map_countries = world_gdf[merge_column_name_gdf].unique()

print("-------------------------------------------------------------------------")
print("Current unique countries in longevity_df_corrected:")
display(longevity_df_corrected['Country Name'].unique())

# Identify countries in longevity_df_corrected that are NOT in map_countries
dropped_countries = longevity_df_corrected[~longevity_df_corrected['Country Name'].isin(map_countries)]['Country Name'].unique()

if len(dropped_countries) > 0:
    print(f"\nCountries from longevity_df_corrected that will be DROPPED (not found in map data): ({len(dropped_countries)} countries)")
    display(pd.Series(dropped_countries))
else:
    print("\nNo countries from longevity_df_corrected need to be dropped based on map data.")

# Filter longevity_df_corrected to only keep countries that are present in map_countries
longevity_df_corrected = longevity_df_corrected[longevity_df_corrected['Country Name'].isin(map_countries)].copy()

print("\nUnique countries in longevity_df_corrected AFTER filtering:")
display(longevity_df_corrected['Country Name'].unique())
print("-------------------------------------------------------------------------")

import geopandas as gpd
import folium
import os
import pandas as pd

# Assuming files are already uploaded in a previous step, and 'uploaded' dict is available.
# If not already defined, ensure global_shp_file_path and longevity_df are available.
# For demonstration, I'll re-initialize them using paths from previous execution.
shp_file_name_uploaded = 'ne_110m_admin_0_countries (3).shp'
global_shp_file_path = os.path.join(os.getcwd(), shp_file_name_uploaded)

world_gdf = gpd.read_file(global_shp_file_path)
longevity_df = pd.read_csv('longevity.csv') # Reload if necessary, or use the existing df from memory

# --- Concise Country Name Mapping and Data Aggregation ---
# Define a mapping for common country name discrepancies
country_name_mapping = {
    'United States': 'United States of America',
    'Congo, Dem. Rep.': 'Dem. Rep. Congo',
    'Congo, Rep.': 'Congo',
    'Egypt, Arab Rep.': 'Egypt',
    'Slovak Republic': 'Slovakia',
    'Micronesia, Fed. Sts.': 'Micronesia',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Yemen, Rep.': 'Yemen',
    'Cote d\'Ivoire': 'Ivory Coast',
    'Eswatini': 'Swaziland',
    'Timor-Leste': 'Timor-Leste',
    'Dominican Republic': 'Dominican Rep.',
    'Equatorial Guinea': 'Eq. Guinea',
    'North Macedonia': 'Macedonia',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'St. Vincent and Grenadines': 'St. Vincent and the Grenadines',
    'Venezuela, RB': 'Venezuela',
    'Bahamas, The': 'Bahamas',
    'Gambia, The': 'Gambia',
    'Cote d\'Ivoire': 'Côte d\'Ivoire',
    'Egypt': 'Egypt, Arab Rep.',
    #'S. Sudan': 'South Sudan',
    'South Sudan': 'S. Sudan',
    'Central African Republic': 'Central African Rep.',
    'Bosnia and Herzegovina': 'Bosnia and Herz.',
    'Czech Republic': 'Czechia',
    'Somaliland': 'Somalia',
    'Eswatini': 'eSwatini',
    #'eSwatini' : 'Eswatini',
    'North Macedonia': 'North Macedonia',


}

# Apply mapping to the 'Country Name' column of longevity_df
# Use .loc to modify the original DataFrame and create a new column if desired
longevity_df_corrected = longevity_df.copy()
longevity_df_corrected['Country Name Mapped'] = longevity_df_corrected['Country Name'].replace(country_name_mapping)

# Now, use the 'Country Name Mapped' for merging
mean_life_expectancy_per_country = longevity_df_corrected.groupby('Country Name Mapped')['Life Expectancy World Bank'].mean().reset_index()

# --- Determine Merge Column and Perform Merge ---
merge_column_name = None
for col in ['NAME', 'name_long', 'sovereign_name', 'admin', 'sovereignt']:
    if col in world_gdf.columns:
        merge_column_name = col
        break

if merge_column_name is None:
    print("Error: No suitable country name column found in GeoDataFrame for merging.")
else:
    merged_gdf_concise = world_gdf.merge(
        mean_life_expectancy_per_country,
        left_on=merge_column_name,
        right_on='Country Name Mapped',
        how='left'
    )

    # Identify countries that did not merge (Life Expectancy is NaN)
    unmatched_countries = merged_gdf_concise[merged_gdf_concise['Life Expectancy World Bank'].isna()]

    print("\nCountries in the map data (world_gdf) that did not find a match in your life expectancy data and are therefore greyed out:")
    # Sort by the merge_column_name for consistent output
    display(unmatched_countries[[merge_column_name, 'Country Name Mapped', 'Life Expectancy World Bank']].drop_duplicates().sort_values(by=merge_column_name))

    # Create a Folium map
    m = folium.Map(location=[0, 0], zoom_start=2)

    # Add the choropleth layer
    folium.Choropleth(
        geo_data=merged_gdf_concise,
        name='choropleth',
        data=merged_gdf_concise,
        columns=[merge_column_name, 'Life Expectancy World Bank'],
        key_on=f'feature.properties.{merge_column_name}',
        fill_color='YlGnBu',
        fill_opacity=0.7,
        line_opacity=0.2,
        legend_name='Global Life Expectancy'
    ).add_to(m)

    # Add layer control to toggle choropleth on/off
    folium.LayerControl().add_to(m)

    # Display the map
    display(m)